### PR TITLE
Add AUTHORS file

### PR DESCRIPTION
**Pull request by codenrhoden**
@clintkitson here is what we discussed with @jonasrosland.

Is this what you were picturing?

### CODE REVIEW

**Comment by akutz** [comment]
So I know we use md for a lot, but for parsing, should this be plain text? Or is this a GitHub-ism?

-- 
-a

**Comment by codenrhoden** [comment]
@akutz I have no strong preference here. I just wanted there to be clickable links for names.

I don't know that there are any plans for parsing this, just for information.

@jonasrosland pointed me to [this](https://github.com/discourse/discourse/blob/master/docs/AUTHORS.md) and [this](https://github.com/facebookincubator/dhcplb/blob/master/AUTHORS) as examples. So, one MD and one non-MD.

**Comment by codenrhoden** [comment]
@akutz pushed a new version after reviewing with Jonas and Clint today. Changed to "REX-Ray Maintainers" to indicate roles. They were good with the .md version - no current plans for parsing this file.

**Comment by jonasrosland** [comment]
LGTM!

**Pull request merged**
